package websecurityshopping;

import java.awt.CardLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gregsimpson
 */
public class ShoppingJApplet extends javax.swing.JApplet {

    ShoppingFrame shopframe;
    //Panel shopframe;
    CardLayout card;
    MainLogin mainlogin = new MainLogin(this);
    NewUserForm userform = new NewUserForm(this);
    
    /**
     * Initializes the applet NewJApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    card = (CardLayout) getContentPane().getLayout();
                    //card.addLayoutComponent(mainlogin, "mainlogin");
                    getContentPane().add(mainlogin, "mainlogin");
                    card.show(getContentPane(), "mainlogin");
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void makeShoppingFrame(){
        getContentPane().add(shopframe, "shopframe");
    }
    
    public void makeShoppingFrame(User user){
        try {
            shopframe = new ShoppingFrame(this, user);
        } catch (SQLException ex) {
            Logger.getLogger(ShoppingJApplet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ShoppingJApplet.class.getName()).log(Level.SEVERE, null, ex);
        }
        //shopframe = new Panel(user);
        getContentPane().add(shopframe, "shopframe");
    }
    
    public void showShoppingFrame(){
        card.show(getContentPane(), "shopframe");
    }
    
    public void makeUserForm(){
        getContentPane().add(userform, "userframe");
    }
    
    public void showUserForm(){
        card.show(getContentPane(), "userframe");
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
